
project:
  type: website
  
website:
  title: "Wiki numerical semigroups"
  sidebar:
    collapse-level: 1
    contents:
      - section: "Basic concepts"
        contents:  
          - Apery-set-respect-set.qmd
          - Apery-set.qmd
          - Arf-closure-set.qmd
          - Arf-closure.qmd
          - Arf-special-gap.qmd
          - Arf-system-of-generators.qmd
          - Binomial-ideal.qmd
          - Cocycle.qmd
          - Conductor.qmd
          - Degree-of-singularity.qmd
          - Depth-and-remainder.qmd
          - Dominant.qmd
          - Eliahou-number.qmd
          - Eliahou-slices.qmd
          - Embedding-dimension.qmd
          - Frobenius-number.qmd
          - Fundamental-gap.qmd
          - Gap.qmd
          - Genus.qmd
          - Gluing.qmd
          - Graph-element-Apery-set.qmd
          - Holes.qmd
          - Homogenization-NS.qmd
          - Irreducible-Z-components.qmd
          - Kunz-coordinates.qmd
          - Kunz-polytope.qmd
          - Lattice-path.qmd
          - Left-elements.qmd
          - MED-closure.qmd
          - MED-system-of-generators.qmd
          - Minimal-set-of-generators.qmd
          - Multiplicity.qmd
          - Nu-sequence.qmd
          - Numerical-semigroup.qmd
          - Oversemigroup.qmd
          - Primitive-element.qmd
          - Profile.qmd
          - Pseudo-Frobenius-number.qmd
          - RF-matrix.qmd
          - Ratio.qmd
          - Relation-order-NS.qmd
          - Saturated-closure.qmd
          - Semigroup-ring.qmd
          - Set-divisors.qmd
          - Special-gap.qmd
          - Standard-representation-free-NS.qmd
          - Tau-sequence.qmd
          - Threshold-interval.qmd
          - Type-sequence.qmd
          - Type.qmd
          - Weierstrass-weight.qmd
          - Wilf-number.qmd
          
      - section: "Families of numerical semigroups"
        contents:
          
          - Arf-irreducible.qmd
          - Arf-semigroup.qmd
          - NS-Apery-set.qmd
          - NS-Dilatation.qmd
          - NS-M-pure.qmd
          - NS-acute.qmd
          - NS-additive.qmd
          - NS-admitting-pattern.qmd
          - NS-almost-symmetric.qmd
          - NS-alpha-rectangular.qmd
          - NS-arithmetic.qmd
          - NS-beta-rectangular.qmd
          - NS-complete-intersection.qmd
          - NS-cyclotomic.qmd
          - NS-duplication.qmd
          - NS-free.qmd
          - NS-gamma-rectangular.qmd
          - NS-generalized-almost-symmetric.qmd
          - NS-generic.qmd
          - NS-gluing.qmd
          - NS-half-line.qmd
          - NS-homogeneous.qmd
          - NS-inductive.qmd
          - NS-irreducible.qmd
          - NS-maximal-embedding-dimension.qmd
          - NS-modular.qmd
          - NS-multiple.qmd
          - NS-plane-branch.qmd
          - NS-prop-modular.qmd
          - NS-pseudo-symmetric.qmd
          - NS-pure.qmd
          - NS-quotient.qmd
          - NS-saturated.qmd
          - NS-set-rational-numbers.qmd
          - NS-shifted.qmd
          - NS-simple.qmd
          - NS-supersymmetric.qmd
          - NS-symmetric.qmd
          - NS-telescopic.qmd
          - NS-unique-Betti-element.qmd
          - NS-uniquely-presented.qmd
          - Pi-semigroup.qmd
          - Weierstrass-semigroup.qmd
          - Wilf-semigroup.qmd

      - section: "Ideals and numerical semigroups"
        contents:
          
          - Almost-canonical-ideal.qmd
          - Apery-set-ideal.qmd
          - Apery-table.qmd
          - Blowup.qmd
          - Canonical-ideal.qmd
          - Conductor-ideal.qmd
          - Conductor-of-an-ideal.qmd
          - Denumerant-ideal.qmd
          - Dual-ideal.qmd
          - Frobenius-number-ideal.qmd
          - Genus-ideal.qmd
          - Hilbert-function-ideal.qmd
          - Ideal-admits-pattern.qmd
          - Integrally-closed-ideal.qmd
          - Irreducible-ideal.qmd
          - Left-elements-ideal.qmd
          - Maximal-ideal.qmd
          - Maximum-sparse-ideal.qmd
          - Microinvariants.qmd
          - Minimal-set-generators-ideal.qmd
          - Multiplicity-ideal.qmd
          - Multiplicity-sequence.qmd
          - Principal-ideal.qmd
          - Proper-ideal.qmd
          - Pseudo-Frobenius-number-ideal.qmd
          - Ratliff-Rush-closure.qmd
          - Ratliff-Rush-number.qmd
          - Reduction-number.qmd
          - Reduction.qmd
          - Relative-ideal.qmd
          - Set-closed-divisors.qmd
          - Stable-ideal.qmd
          - Standard-canonical-ideal.qmd
          - Star-closure.qmd
          - Trace-ideal.qmd
          - Translation-ideal.qmd
          - Type-ideal.qmd
          - Z-irreducible-ideal.qmd
      
      - section: "Factorizations and divisibility"
        contents: 
          
          - Adjacent-catenary-degree-element.qmd
          - Adjustment-NS.qmd
          - Adjustment-of-an-element.qmd
          - Apery-set-integer.qmd
          - Catenary-degree-of-a-numerical-semigroup.qmd
          - Catenary-degree-of-an-element.qmd
          - Chain-of-factorizations.qmd
          - Delta-set-of-a-numerical-semigroup.qmd
          - Delta-set-of-an-element.qmd
          - Desert.qmd
          - Distance-factorizations.qmd
          - Divide.qmd
          - Elasticity-of-a-numerical-semigroup.qmd
          - Elasticity-of-an-element.qmd
          - Equal-catenary-degree-NS.qmd
          - Equal-catenary-degree-element.qmd
          - Feng-Rao-distance-generalized.qmd
          - Feng-Rao-distance.qmd
          - Half-factorial-monoid.qmd
          - Length-factorization.qmd
          - Maximal-denumerant-NS.qmd
          - Maximal-denumerant-of-an-element.qmd
          - Moebius-function-NS.qmd
          - Monotone-catenary-degree-NS.qmd
          - Monotone-catenary-degree-element.qmd
          - One-point-algebraic-code.qmd
          - Order-of-an-element.qmd
          - Set-of-lengths.qmd
          - Tame-degree-of-a-numerical-semigroup.qmd
          - Tame-degree-of-an-element.qmd
          - w-primality-of-a-numerical-semigroup.qmd
          - w-primality-of-an-element.qmd

      - section: "Frobenius varieties"
        contents:
          - Varieties-NS/Chain-associated-NS.qmd
          - Varieties-NS/Directed-graph-all-NS.qmd
          - Varieties-NS/Frobenius-variety-generated-NS.qmd
          - Varieties-NS/Frobenius-variety.qmd
          - Varieties-NS/Pattern.qmd
          - Varieties-NS/V-monoid.qmd
      
      - section: "Presentations of a numerical smeigroup"
        contents:
          - Presentations-NS/Betti-element.qmd
          - Presentations-NS/Congruence-compatible.qmd
          - Presentations-NS/Congruence-set.qmd
          - Presentations-NS/Factorization-homomorphism.qmd
          - Presentations-NS/Factorizations-R-related.qmd
          - Presentations-NS/Graph-associated-to-an-element.qmd
          - Presentations-NS/Graph-element-generators.qmd
          - Presentations-NS/Hilbert-series.qmd
          - Presentations-NS/Presentation-NS.qmd
          - Presentations-NS/Set-of-factorizations.qmd
          - Presentations-NS/Shaded-set.qmd

      - section: "Proportionally modular numerical semigroups"
        contents:
          - Prop-modular-NS/Adjacent-fractions.qmd
          - Prop-modular-NS/Bezout-sequence.qmd
          - Prop-modular-NS/Factor-prop-mod-Diophantine-ineq.qmd
          - Prop-modular-NS/Mod-Diophantine-ineq.qmd
          - Prop-modular-NS/Modulus-prop-mod-Diophantine-ineq.qmd
          - Prop-modular-NS/Period-of-a-subadditive-function.qmd
          - Prop-modular-NS/Prop-mod-Diophantine-ineq.qmd
          - Prop-modular-NS/Proper-Bezout-sequence.qmd
          - Prop-modular-NS/Proportion-prop-mod-Diophantine-ineq.qmd
          - Prop-modular-NS/Subadditive-function.qmd
          - Prop-modular-NS/Weight-mod-Diophantine-ineq.qmd

      - section: "The structure of a numerical semigroup"
        contents:
          - Structure-NS/Archimedean-property.qmd
          - Structure-NS/Congruence-on-a-semigroup.qmd
          - Structure-NS/M-cancellative.qmd
          - Structure-NS/M-hereditarily-finitely-generated.qmd
          - Structure-NS/M-quasi-Archimedean.qmd
          - Structure-NS/M-weakly-cancellative.qmd
          - Structure-NS/Quotient-group-monoid.qmd
          - Structure-NS/R-monoid.qmd
          - Structure-NS/S-multiple-joined.qmd
          - Structure-NS/S-torsion-free.qmd

      - section: "Semigroup of an irreducible meromorphic series"
        contents:
          - Meromorphic-series-NS/Approximate-root.qmd
          - Meromorphic-series-NS/Characteristic-sequences.qmd
          - Meromorphic-series-NS/Contact.qmd
          - Meromorphic-series-NS/Curve-NS.qmd
          - Meromorphic-series-NS/Curves-one-place-infinity.qmd
          - Meromorphic-series-NS/Exact-degree-algebroid-curve.qmd
          - Meromorphic-series-NS/Exact-degree-polynomial-curve.qmd
          - Meromorphic-series-NS/Expansion.qmd
          - Meromorphic-series-NS/G-adic-expansion.qmd
          - Meromorphic-series-NS/Intersection-multiplicity.qmd
          - Meromorphic-series-NS/Milnor-number.qmd
          - Meromorphic-series-NS/Newton-Puiseux-exponents.qmd
          - Meromorphic-series-NS/Order.qmd
          - Meromorphic-series-NS/Polynomial-NS.qmd
          - Meromorphic-series-NS/Pseudo-approximate-root.qmd
          - Meromorphic-series-NS/Short-parametrization.qmd
          - Meromorphic-series-NS/Support.qmd
          - Meromorphic-series-NS/Tschirnhausen-transform.qmd
          - Meromorphic-series-NS/Very-short-parametrization.qmd
